# development project.yaml
---
example::path: "/tmp/example_project_dev.txt"
example::path_extended: "/tmp/extended_project_dev.txt"
example::content: "project_dev"
# --------------
# composer
# --------------
composer::bindir:      "/usr/local/bin"
composer::filename:    "composer"
composer::run_install: "no"
composer::run_update:  "no"